# ────────────────────────────────────────────────────────────────────────────────
# Stage 1: Builder
# ────────────────────────────────────────────────────────────────────────────────
FROM node:18-alpine AS builder

WORKDIR /app

ARG SALT_ROUNDS
ENV SALT_ROUNDS=${SALT_ROUNDS}

RUN apk add --no-cache python3 g++ make

COPY package*.json tsconfig.json ./
COPY prisma ./prisma

RUN npm ci
RUN npm run generate:dev

COPY src ./src
RUN npm run build

# ────────────────────────────────────────────────────────────────────────────────
# Stage 2: Runtime (Produção)
# ────────────────────────────────────────────────────────────────────────────────
FROM node:18-alpine

WORKDIR /app

ARG NODE_ENV
ARG PORT_BACKEND

ENV NODE_ENV=${NODE_ENV}
ENV PORPORT_BACKENDT=${PORT_BACKEND}

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/prisma ./prisma

EXPOSE ${PORT_BACKEND}

CMD ["sh", "-c", "npm run migrate:deploy && npm run seed:prod && node dist/src/server.js"]