FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 g++ make

COPY package*.json tsconfig.json ./
COPY prisma ./prisma

RUN npm ci
RUN npm run generate:dev

RUN npm install -g nodemon ts-node

EXPOSE ${PORT_BACKEND}

CMD ["npm", "run", "dev"]