name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Confirm and Deploy
        run: |
          echo "Deploying to production..."
          # ex.: ./scripts/deploy-production.sh