name: Deploy to Staging

on:
  workflow_run:
    workflows: ["End-to-End Tests"]
    types: [completed]

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Deploying to staging..."
          # ex.: ./scripts/deploy-staging.sh